version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./ai/mis_melodias:/app/ai/mis_melodias
      - ./ai/uploads:/app/ai/uploads
      - ./users.db:/app/users.db

  frontend:
    image: python:3.10-slim
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "8001:8001"
    command: python -m http.server 8001
